// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicTaglineBanner,
  DefaultTaglineBannerProps
} from "./plasmic/dirt/PlasmicTaglineBanner";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface TaglineBannerProps extends Omit<DefaultTaglineBannerProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultTaglineBannerProps altogether and have
// total control over the props for your component.
export interface TaglineBannerProps extends DefaultTaglineBannerProps {}

function TaglineBanner_(props: TaglineBannerProps, ref: HTMLElementRefOf<"a">) {
  // Use PlasmicTaglineBanner to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicTaglineBanner are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all TaglineBannerProps here, but feel free
  // to do whatever works for you.

  return <PlasmicTaglineBanner taglineBanner={{ ref }} {...props} />;
}

const TaglineBanner = React.forwardRef(TaglineBanner_);
export default TaglineBanner;
