/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8kaaMUEQHxomwqwuKNMozy
// Component: wWD7id8LzFyR

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { DirtNav } from "../../sections/DirtNav"; // plasmic-import: CKU2TJ7qFh0A/codeComponent
import { DirtNavLink } from "../../sections/DirtNavLink"; // plasmic-import: djxf9UfRwps8/codeComponent
import { DirtRichText } from "../../sections/DirtRichText"; // plasmic-import: nKt2zrpkFSyY/codeComponent
import { FooterSection } from "../../sections/FooterSection"; // plasmic-import: I7Z-mxcvFz5C/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/projectcss
import sty from "./PlasmicNewsletter.module.css"; // plasmic-import: wWD7id8LzFyR/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    title: "Newsletter - DIRT",
    description:
      "In industries where every bid and every project counts, the brands that communicate best will win again and again. We know exactly how to create memorable, project-winning brands. In fact, we’ve done it for years.",
    openGraph: {
      title: "Newsletter - DIRT",
      description:
        "In industries where every bid and every project counts, the brands that communicate best will win again and again. We know exactly how to create memorable, project-winning brands. In fact, we’ve done it for years."
    },
    twitter: {
      card: "summary",
      title: "Newsletter - DIRT",
      description:
        "In industries where every bid and every project counts, the brands that communicate best will win again and again. We know exactly how to create memorable, project-winning brands. In fact, we’ve done it for years."
    },
    alternates: { canonical: "/about" }
  };
}

createPlasmicElementProxy;

export type PlasmicNewsletter__VariantMembers = {};
export type PlasmicNewsletter__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewsletter__VariantsArgs;
export const PlasmicNewsletter__VariantProps = new Array<VariantPropType>();

export type PlasmicNewsletter__ArgsType = {};
type ArgPropType = keyof PlasmicNewsletter__ArgsType;
export const PlasmicNewsletter__ArgProps = new Array<ArgPropType>();

export type PlasmicNewsletter__OverridesType = {
  root?: Flex__<"div">;
  dirtNav?: Flex__<typeof DirtNav>;
  link?: Flex__<"a"> & Partial<LinkProps>;
  dirtRichText?: Flex__<typeof DirtRichText>;
  footerSection?: Flex__<typeof FooterSection>;
};

export interface DefaultNewsletterProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNewsletter__RenderFunc(props: {
  variants: PlasmicNewsletter__VariantsArgs;
  args: PlasmicNewsletter__ArgsType;
  overrides: PlasmicNewsletter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
        <meta
          key="description"
          property="description"
          content={pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={pageMetadata.description}
        />
        <meta
          key="twitter:description"
          property="twitter:description"
          content={pageMetadata.description}
        />

        <link rel="canonical" href={pageMetadata.alternates?.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <DirtNav
            data-plasmic-name={"dirtNav"}
            data-plasmic-override={overrides.dirtNav}
            actions={
              <PlasmicLink__
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link
                )}
                component={Link}
                href={`/contact`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Contact Us"}
              </PlasmicLink__>
            }
            className={classNames("__wab_instance", sty.dirtNav)}
            logo={"/plasmic/dirt/images/dirtFinalIdentityLogos06Png.png"}
            menuBackground={"dirt-pop"}
            menuImage={"/plasmic/dirt/images/menuImagePng.png"}
            menuLinks={
              <React.Fragment>
                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__vdrfa
                  )}
                  href={"/about"}
                  label={"About"}
                />

                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__qzdyE
                  )}
                  href={"/contact"}
                  label={"Contact"}
                />
              </React.Fragment>
            }
            navBackground={"transparent"}
          />

          <section className={classNames(projectcss.all, sty.section__r2Ok8)}>
            <div className={classNames(projectcss.all, sty.freeBox__b2Ydi)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vf9Jb
                )}
              >
                {
                  "The best newsletter in your inbox. If it\u2019s not, we\u2019ll backfill"
                }
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__jvJzU)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/dirt/images/littleShovelPng.png",
                  fullWidth: 56,
                  fullHeight: 56,
                  aspectRatio: undefined
                }}
              />
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__oQpX2)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__eBuX4
              )}
            >
              {"The newsletter where nothing stays buried."}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__cFxK)}>
              <DirtRichText
                data-plasmic-name={"dirtRichText"}
                data-plasmic-override={overrides.dirtRichText}
                className={classNames("__wab_instance", sty.dirtRichText)}
                text={
                  "Digging up branding insights, concrete messaging examples, and sharp takes on positioning. Delivered bi-monthly({blue|ish|or whenever the dirt settles}).\n\nFor construction, contech, and building material teams who suspect their brand is holding them back."
                }
                textColour={"dirt-deep"}
              />
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__jBqyz)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aRqAb
              )}
            >
              {"Unearth the good stuff"}
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___3HbcW)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kHady
              )}
            >
              {"Bet you\u2019ll love it as much as these subscribers"}
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__bJn8)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__bicuv)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"590px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/dirt/images/testimonial01Jpg.jpg",
                  fullWidth: 593,
                  fullHeight: 247,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ly4ET)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"590px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/dirt/images/testimonial01Jpg.jpg",
                  fullWidth: 593,
                  fullHeight: 247,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__pWmrD)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"590px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/dirt/images/testimonial03Jpg.jpg",
                  fullWidth: 593,
                  fullHeight: 205,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ck4KO)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"590px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/dirt/images/testimonial03Jpg.jpg",
                  fullWidth: 593,
                  fullHeight: 205,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__dMZt)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"590px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/dirt/images/testimonial01Jpg.jpg",
                  fullWidth: 593,
                  fullHeight: 247,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___6Ym0X)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"590px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/dirt/images/testimonial01Jpg.jpg",
                  fullWidth: 593,
                  fullHeight: 247,
                  aspectRatio: undefined
                }}
              />
            </div>
          </section>
          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            backgroundImage={"/plasmic/dirt/images/footerImagePng.png"}
            bottomRightLink={"/"}
            bottomRightText={"Click here to  toss some DIRT on the competition"}
            className={classNames("__wab_instance", sty.footerSection)}
            contactDescription={`Dig what we're doing but don't need us at the moment? Refer a client to DIRT. 

When they sign on, we'll send you a 5% referral fee. (A little thank you for spreading the DIRT)`}
            contactHeading={"Refer & Earn"}
            copyrightText={
              "\u00a9 2026 DIRT Agency. All rights reserved. Built from the ground up."
            }
            description={
              "Tell us your DIRTiest dreams and we'll make them come true:"
            }
            footerDescription={
              "Fresh messaging, branding, and positioning from the ground up."
            }
            footerLogo={"/plasmic/dirt/images/dirtFinalIdentityLogos06Png.png"}
            heading1={"Brilliant brands don\u2019t grow on trees."}
            heading2={"They grow in the DIRT."}
            link1Text={"About"}
            link1Url={"/about"}
            link2Text={"Contact"}
            link2Url={"/contact"}
            linksHeading={"Get your hands dirty"}
            mobileBackgroundImage={
              "/plasmic/dirt/images/mobileFooterDirtBackgroundPng.png"
            }
            newsletterDescription={
              "Gritty strategic insights to help you win more clients. Delivered with love (and a smidge of mud) once monthly."
            }
            newsletterHeading={"Get Dirt Dispatch"}
            recipientEmail={"hello@thedirtagency.com"}
            separatorImage={"/plasmic/dirt/images/line2Png.png"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___9ZFcq
            )}
          >
            {"Enter some text"}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dirtNav", "link", "dirtRichText", "footerSection"],
  dirtNav: ["dirtNav", "link"],
  link: ["link"],
  dirtRichText: ["dirtRichText"],
  footerSection: ["footerSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dirtNav: typeof DirtNav;
  link: "a";
  dirtRichText: typeof DirtRichText;
  footerSection: typeof FooterSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewsletter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewsletter__VariantsArgs;
    args?: PlasmicNewsletter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNewsletter__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNewsletter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewsletter__ArgProps,
          internalVariantPropNames: PlasmicNewsletter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewsletter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewsletter";
  } else {
    func.displayName = `PlasmicNewsletter.${nodeName}`;
  }
  return func;
}

export const PlasmicNewsletter = Object.assign(
  // Top-level PlasmicNewsletter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dirtNav: makeNodeComponent("dirtNav"),
    link: makeNodeComponent("link"),
    dirtRichText: makeNodeComponent("dirtRichText"),
    footerSection: makeNodeComponent("footerSection"),

    // Metadata about props expected for PlasmicNewsletter
    internalVariantProps: PlasmicNewsletter__VariantProps,
    internalArgProps: PlasmicNewsletter__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/newsletter",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicNewsletter;
/* prettier-ignore-end */
