/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8kaaMUEQHxomwqwuKNMozy
// Component: j_vMVTQjFfxV

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useMutablePlasmicQueryData } from "@plasmicapp/query";

import { usePlasmicQueries } from "@plasmicapp/react-web/lib/data-sources";
import type {
  PlasmicQuery,
  PlasmicQueryResult
} from "@plasmicapp/react-web/lib/data-sources";
import type { QueryComponentNode } from "@plasmicapp/react-web/lib/data-sources";

import { DirtNav } from "../../sections/DirtNav"; // plasmic-import: CKU2TJ7qFh0A/codeComponent
import { DirtNavLink } from "../../sections/DirtNavLink"; // plasmic-import: djxf9UfRwps8/codeComponent
import { NewsletterFormSection } from "../../sections/NewsletterFormSection"; // plasmic-import: XfKpmE3Hd3LP/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicBlog.module.css"; // plasmic-import: j_vMVTQjFfxV/css

import { fetchContent as __fn_plasmicCms__fetchContent } from "@plasmicpkgs/cms";

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Dispatch",

    openGraph: {
      title: "Dispatch"
    },
    twitter: {
      card: "summary" as const,
      title: "Dispatch"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicBlog__VariantMembers = {};
export type PlasmicBlog__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlog__VariantsArgs;
export const PlasmicBlog__VariantProps = new Array<VariantPropType>();

export type PlasmicBlog__ArgsType = {};
type ArgPropType = keyof PlasmicBlog__ArgsType;
export const PlasmicBlog__ArgProps = new Array<ArgPropType>();

export type PlasmicBlog__OverridesType = {
  root?: Flex__<"div">;
  dirtNav?: Flex__<typeof DirtNav>;
  h1?: Flex__<"h1">;
  h3?: Flex__<"h3">;
  newsletterFormSection?: Flex__<typeof NewsletterFormSection>;
};

export interface DefaultBlogProps {}

const $$ = {
  plasmicCms: {
    fetchContent: __fn_plasmicCms__fetchContent
  }
};

export const serverQueryTree: QueryComponentNode = {
  type: "component",
  queries: {
    query: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsPublicToken: null,
            cmsId: null,
            tableId: null,
            orderBy: null,
            orderDirection: null,
            offset: null
          };
          __composite["cmsPublicToken"] =
            "SEDPH2yp15PlCcWNciTlp1E5wPDR5TvMxlZienZrDz8CxW3LaZkyZan3a8SYXGum1ZR0xOLLh9KmanzfqsQ";
          __composite["cmsId"] = "oddQjnTUVWDpYkuyZHTBcK";
          __composite["tableId"] = "articles";
          __composite["orderBy"] = "publishedDate";
          __composite["orderDirection"] = "desc";
          __composite["offset"] = 0;
          return __composite;
        })()
      ]
    },
    authors: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsId: null,
            cmsPublicToken: null,
            tableId: null
          };
          __composite["cmsId"] = "oddQjnTUVWDpYkuyZHTBcK";
          __composite["cmsPublicToken"] =
            "Oq9HoSuLbH8xdIIUvRFBwjXFzBdrqx4S2jNviKrGncu8V47IRi1QctzJsiHhRH09AZHTuxps8bHVAPU5oGMQ";
          __composite["tableId"] = "authors";
          return __composite;
        })()
      ]
    },
    categories: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsPublicToken: null,
            cmsId: null,
            tableId: null
          };
          __composite["cmsPublicToken"] =
            "SEDPH2yp15PlCcWNciTlp1E5wPDR5TvMxlZienZrDz8CxW3LaZkyZan3a8SYXGum1ZR0xOLLh9KmanzfqsQ";
          __composite["cmsId"] = "oddQjnTUVWDpYkuyZHTBcK";
          __composite["tableId"] = "categories";
          return __composite;
        })()
      ]
    }
  },
  propsContext: {},
  stateSpecs: [
    {
      path: "selectedCategory",
      type: "private",
      variableType: "text",
      initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
    }
  ],
  children: []
};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBlog__RenderFunc(props: {
  variants: PlasmicBlog__VariantsArgs;
  args: PlasmicBlog__ArgsType;
  overrides: PlasmicBlog__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "selectedCategory",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $stateRef = React.useRef<Record<string, unknown> | null>(null);
  const $q = usePlasmicQueries(serverQueryTree, {
    $ctx,
    $props,
    $state: $stateRef.current
  });

  const globalVariants = _useGlobalVariants();

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: $q,
    $refs
  });
  $stateRef.current = $state;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy($q),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{pageMetadata.title}</title>
        <meta key="og:title" property="og:title" content={pageMetadata.title} />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_8kaaMUEQHxomwqwuKNMozy",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <DirtNav
            data-plasmic-name={"dirtNav"}
            data-plasmic-override={overrides.dirtNav}

            className={classNames("__wab_instance", sty.dirtNav)}
            logo={"/plasmic/dirt/images/dirtFinalIdentityLogos06Png.png"}
            menuBackground={"dirt-pop"}
            menuImage={"/plasmic/dirt/images/menuImagePng.png"}
            menuLinks={
              <React.Fragment>
                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__fXg5Q
                  )}
                  href={"/"}
                  label={"Home"}
                />

                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__txzde
                  )}
                  href={"/about"}
                  label={"About"}
                />

                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__ekd1H
                  )}
                  href={"/services"}
                  label={"Services"}
                />

                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__k7Q8E
                  )}
                  href={"/contact"}
                  label={"Contact"}
                />
              </React.Fragment>
            }
            navBackground={"dirt-deep"}
            stickyOnScroll={false}
          />

          <section className={classNames("all", sty.section___4AWga)}>
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}

              className={classNames(
                "all",
                "h1",
                "h1__8kaaM",
                "__wab_text",
                sty.h1
              )}
            >
              {hasVariant(globalVariants, "screen", "mobile") ? (
                <React.Fragment>
                  <React.Fragment>{"A very strong and catchy"}</React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__8kaaM"
                    }
                    style={{ color: "var(--token-5joSP94EMVrt)" }}
                  >
                    {" nikita-esque"}
                  </span>
                  <React.Fragment>{" title"}</React.Fragment>
                </React.Fragment>
              ) : (
                <React.Fragment>
                  <React.Fragment>
                    {"A very strong and catchy\r\n"}
                  </React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__8kaaM"
                    }
                    style={{ color: "var(--token-5joSP94EMVrt)" }}
                  >
                    {"nikita-esque"}
                  </span>
                  <React.Fragment>{" title"}</React.Fragment>
                </React.Fragment>
              )}
            </h1>
            <div className={classNames("all", "__wab_text", sty.text__xeaIs)}>
              <React.Fragment>
                <React.Fragment>
                  {
                    "In industries where every bid and every project counts, the brands that communicate best will win again and again. "
                  }
                </React.Fragment>
                <span
                  className={
                    "plasmic_default__all plasmic_default__span plasmic_default__span__8kaaM"
                  }
                  style={{ fontWeight: 700 }}
                >
                  {
                    "We know exactly how to create memorable, project-winning brands."
                  }
                </span>
                <React.Fragment>
                  {" In fact, we\u2019ve done it for years."}
                </React.Fragment>
              </React.Fragment>
            </div>
          </section>
          <section className={classNames("all", sty.section__c1VZj)}>
            <div className={classNames("all", sty.freeBox__yrqvu)}>
              <div className={classNames("all", "__wab_text", sty.text__on5Vu)}>
                {"Featured"}
              </div>
              <h2
                className={classNames(
                  "all",
                  "h2",
                  "h2__8kaaM",
                  "__wab_text",
                  sty.h2__kzGx
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $q.query.data[0].data.title;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </h2>
              <div className={classNames("all", "__wab_text", sty.text__mn9FN)}>
                <React.Fragment>{$q.query.data[0].data.excerpt}</React.Fragment>
              </div>
              <div className={classNames("all", sty.freeBox__kuc65)}>
                <div
                  className={classNames("all", "__wab_text", sty.text__krVb0)}
                >
                  <React.Fragment>
                    {
                      $q.authors.data.find(
                        author => author.id === $q.query.data[0].data.author
                      )?.data.name
                    }
                  </React.Fragment>
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__vLfcJ)}
                >
                  {"\u00b7"}
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__s9Kh3)}
                >
                  <React.Fragment>
                    {Math.max(
                      1,
                      Math.ceil(
                        ($q.query.data[0].data.body || "")
                          .replace(/<[^>]*>/g, " ")
                          .trim()
                          .split(/\s+/).length / 200
                      )
                    ) + " min read"}
                  </React.Fragment>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames("all", sty.section__t7Dqp)}>
            <div className={classNames("all", sty.freeBox__mseZo)}>
              <div className={classNames("all", sty.freeBox__ucq7D)}>
                {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                  (() => {
                    try {
                      return $q.categories.data;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                ).map((__plasmic_item_0, __plasmic_idx_0) => {
                  const currentItem = __plasmic_item_0;
                  const currentIndex = __plasmic_idx_0;
                  return (
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__dSmNs
                      )}
                      key={currentIndex}
                      onClick={async event => {
                        const $steps = {};

                        $steps["updateSelectedCategory"] = true
                          ? (() => {
                              const actionArgs = {
                                variable: {
                                  objRoot: $state,
                                  variablePath: ["selectedCategory"]
                                },
                                operation: 0,
                                value:
                                  $state.selectedCategory === currentItem.id
                                    ? ""
                                    : currentItem.id
                              };
                              return (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                $stateSet(objRoot, variablePath, value);
                                return value;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updateSelectedCategory"] != null &&
                          typeof $steps["updateSelectedCategory"] ===
                            "object" &&
                          typeof $steps["updateSelectedCategory"].then ===
                            "function"
                        ) {
                          $steps["updateSelectedCategory"] =
                            await $steps["updateSelectedCategory"];
                        }
                      }}
                      style={{
                        color: currentItem.data.colour,
                        opacity:
                          $state.selectedCategory === currentItem.id ? 1 : 0.5,
                        cursor: "pointer"
                      }}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return currentItem.data.name;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "currentItem.data.name";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  );
                })}
              </div>
            </div>
          </section>
          <section className={classNames("all", sty.section__bxSlg)}>
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $q.query.data
                    .slice(1)
                    .filter(
                      article =>
                        !$state.selectedCategory ||
                        article.data.category === $state.selectedCategory
                    );
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <div
                  className={classNames("all", sty.freeBox__hsg1P)}
                  key={currentIndex}
                >
                  <div className={classNames("all", sty.freeBox__bhRu8)}>
                    <h2
                      className={classNames(
                        "all",
                        "h2",
                        "h2__8kaaM",
                        "__wab_text",
                        sty.h2___480Pg
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return currentItem.data.title;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "The Title of an article here\r\nthat you want list next";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </h2>
                    <div
                      className={classNames(
                        "all",
                        "__wab_text",
                        sty.text__hwR7O
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return currentItem.data.excerpt;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "In industries where every bid and every project counts, the brands that communicate best will win again and again. We know exactly how to create memorable, project-winning brands.";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </div>
                  <div
                    className={classNames("all", "__wab_text", sty.text__yIGss)}
                    style={{
                      color: $q.categories.data.find(
                        category => category.id === currentItem.data.category
                      )?.data.colour
                    }}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $q.categories.data.find(
                            category =>
                              category.id === currentItem.data.category
                          )?.data.name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Dispatch";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
              );
            })}
          </section>
          <section className={classNames("all", sty.section___6Nvk)}>
            <div className={classNames("all", sty.freeBox__cgVfb)}>
              <h3
                data-plasmic-name={"h3"}
                data-plasmic-override={overrides.h3}

                className={classNames(
                  "all",
                  "h3",
                  "h3__8kaaM",
                  "__wab_text",
                  sty.h3
                )}
              >
                {"Get it in your inbox first\r"}
              </h3>
              <div className={classNames("all", "__wab_text", sty.text__qi8P3)}>
                {hasVariant(globalVariants, "screen", "tablet")
                  ? "Digging up branding insights, concrete messaging examples, and sharp takes on positioning. Delivered bi-monthly(ish).\r\n"
                  : "Digging up branding insights, concrete messaging examples,\r\nand sharp takes on positioning. Delivered bi-monthly(ish).\r\n"}
              </div>
              <NewsletterFormSection
                data-plasmic-name={"newsletterFormSection"}
                data-plasmic-override={overrides.newsletterFormSection}

                className={classNames(
                  "__wab_instance",
                  sty.newsletterFormSection
                )}
                submitButtonLabel={"Subscribe"}
                successMessage={"Thanks for subscribing!"}
                successMessageColour={"dirt-green"}
              />
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dirtNav", "h1", "h3", "newsletterFormSection"],
  dirtNav: ["dirtNav"],
  h1: ["h1"],
  h3: ["h3"],
  newsletterFormSection: ["newsletterFormSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dirtNav: typeof DirtNav;
  h1: "h1";
  h3: "h3";
  newsletterFormSection: typeof NewsletterFormSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlog__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlog__VariantsArgs;
    args?: PlasmicBlog__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicBlog__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicBlog__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBlog__ArgProps,
          internalVariantPropNames: PlasmicBlog__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBlog__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlog";
  } else {
    func.displayName = `PlasmicBlog.${nodeName}`;
  }
  return func;
}

export const PlasmicBlog = Object.assign(
  // Top-level PlasmicBlog renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dirtNav: makeNodeComponent("dirtNav"),
    h1: makeNodeComponent("h1"),
    h3: makeNodeComponent("h3"),
    newsletterFormSection: makeNodeComponent("newsletterFormSection"),

    // Metadata about props expected for PlasmicBlog
    internalVariantProps: PlasmicBlog__VariantProps,
    internalArgProps: PlasmicBlog__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/blog",
      pagePath: "/blog",
      params: {},
      query: {}
    })
  }
);

export default PlasmicBlog;
/* prettier-ignore-end */
