/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8kaaMUEQHxomwqwuKNMozy

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantszo7Fk0Idbz1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zo7FK0idbz_1/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantszo7Fk0Idbz1
});
