/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8kaaMUEQHxomwqwuKNMozy
// Component: Boo0whzpC_1V

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useMutablePlasmicQueryData } from "@plasmicapp/query";

import { usePlasmicQueries } from "@plasmicapp/react-web/lib/data-sources";
import type {
  PlasmicQuery,
  PlasmicQueryResult
} from "@plasmicapp/react-web/lib/data-sources";
import type { QueryComponentNode } from "@plasmicapp/react-web/lib/data-sources";

import { DirtNav } from "../../sections/DirtNav"; // plasmic-import: CKU2TJ7qFh0A/codeComponent
import { DirtNavLink } from "../../sections/DirtNavLink"; // plasmic-import: djxf9UfRwps8/codeComponent
import { NewsletterFormSection } from "../../sections/NewsletterFormSection"; // plasmic-import: XfKpmE3Hd3LP/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicArticlesTemplate.module.css"; // plasmic-import: Boo0whzpC_1V/css

import { fetchContent as __fn_plasmicCms__fetchContent } from "@plasmicpkgs/cms";

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicArticlesTemplate__VariantMembers = {};
export type PlasmicArticlesTemplate__VariantsArgs = {};
type VariantPropType = keyof PlasmicArticlesTemplate__VariantsArgs;
export const PlasmicArticlesTemplate__VariantProps =
  new Array<VariantPropType>();

export type PlasmicArticlesTemplate__ArgsType = {};
type ArgPropType = keyof PlasmicArticlesTemplate__ArgsType;
export const PlasmicArticlesTemplate__ArgProps = new Array<ArgPropType>();

export type PlasmicArticlesTemplate__OverridesType = {
  root?: Flex__<"div">;
  dirtNav?: Flex__<typeof DirtNav>;
  img?: Flex__<typeof PlasmicImg__>;
  newsletterFormSection?: Flex__<typeof NewsletterFormSection>;
};

export interface DefaultArticlesTemplateProps {}

const $$ = {
  plasmicCms: {
    fetchContent: __fn_plasmicCms__fetchContent
  }
};

export const serverQueryTree: QueryComponentNode = {
  type: "component",
  queries: {
    articles: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsPublicToken: null,
            cmsId: null,
            tableId: null,
            orderBy: null,
            orderDirection: null,
            offset: null
          };
          __composite["cmsPublicToken"] =
            "SEDPH2yp15PlCcWNciTlp1E5wPDR5TvMxlZienZrDz8CxW3LaZkyZan3a8SYXGum1ZR0xOLLh9KmanzfqsQ";
          __composite["cmsId"] = "oddQjnTUVWDpYkuyZHTBcK";
          __composite["tableId"] = "articles";
          __composite["orderBy"] = "publishedDate";
          __composite["orderDirection"] = "desc";
          __composite["offset"] = 0;
          return __composite;
        })()
      ]
    },
    authors: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsId: null,
            cmsPublicToken: null,
            tableId: null
          };
          __composite["cmsId"] = "oddQjnTUVWDpYkuyZHTBcK";
          __composite["cmsPublicToken"] =
            "Oq9HoSuLbH8xdIIUvRFBwjXFzBdrqx4S2jNviKrGncu8V47IRi1QctzJsiHhRH09AZHTuxps8bHVAPU5oGMQ";
          __composite["tableId"] = "authors";
          return __composite;
        })()
      ]
    },
    categories: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsPublicToken: null,
            cmsId: null,
            tableId: null
          };
          __composite["cmsPublicToken"] =
            "SEDPH2yp15PlCcWNciTlp1E5wPDR5TvMxlZienZrDz8CxW3LaZkyZan3a8SYXGum1ZR0xOLLh9KmanzfqsQ";
          __composite["cmsId"] = "oddQjnTUVWDpYkuyZHTBcK";
          __composite["tableId"] = "categories";
          return __composite;
        })()
      ]
    }
  },
  propsContext: {},
  stateSpecs: [],
  children: []
};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicArticlesTemplate__RenderFunc(props: {
  variants: PlasmicArticlesTemplate__VariantsArgs;
  args: PlasmicArticlesTemplate__ArgsType;
  overrides: PlasmicArticlesTemplate__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $q = usePlasmicQueries(serverQueryTree, { $ctx, $props, $state: null });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy($q),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_8kaaMUEQHxomwqwuKNMozy",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <DirtNav
            data-plasmic-name={"dirtNav"}
            data-plasmic-override={overrides.dirtNav}

            className={classNames("__wab_instance", sty.dirtNav)}
            logo={"/plasmic/dirt/images/dirtFinalIdentityLogos06Png.png"}
            menuBackground={"dirt-pop"}
            menuImage={"/plasmic/dirt/images/menuImagePng.png"}
            menuLinks={
              <React.Fragment>
                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__uEb6S
                  )}
                  href={"/"}
                  label={"Home"}
                />

                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__tBuBs
                  )}
                  href={"/about"}
                  label={"About"}
                />

                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__szMhc
                  )}
                  href={"/services"}
                  label={"Services"}
                />

                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__dq5Sc
                  )}
                  href={"/contact"}
                  label={"Contact"}
                />
              </React.Fragment>
            }
            navBackground={"dirt-black"}
            stickyOnScroll={false}
          />

          <section className={classNames("all", sty.section___3YlKg)}>
            <div className={classNames("all", sty.freeBox___6Jh8O)}>
              <div className={classNames("all", "__wab_text", sty.text__ofBeU)}>
                <React.Fragment>
                  {
                    $q.categories.data.find(
                      c =>
                        c.id ===
                        $q.article.data.find(
                          a => a.data.slug === $ctx.params.slug
                        )?.data.category
                    )?.data.name
                  }
                </React.Fragment>
              </div>
              <h1
                className={classNames(
                  "all",
                  "h1",
                  "h1__8kaaM",
                  "__wab_text",
                  sty.h1__kTig7
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $q.article.data.find(
                        a => a.data.slug === $ctx.params.slug
                      )?.data.title;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "You won't believe what happens next.";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </h1>
              <div className={classNames("all", "__wab_text", sty.text__k9Ee)}>
                <React.Fragment>
                  {
                    $q.article.data.find(a => a.data.slug === $ctx.params.slug)
                      ?.data.excerpt
                  }
                </React.Fragment>
              </div>
            </div>
            <div className={classNames("all", sty.freeBox__vD0D5)}>
              <div
                className={classNames("all", "__wab_text", sty.text___07Y61)}
              >
                {"Nikita Morell"}
              </div>
              <div className={classNames("all", "__wab_text", sty.text__b2E4O)}>
                {"May 2026"}
              </div>
            </div>
          </section>
          <section className={classNames("all", sty.section__tytWo)}>
            <div className={classNames("all", "__wab_text", sty.text__xufm9)}>
              <React.Fragment>
                {
                  $q.article.data.find(a => a.data.slug === $ctx.params.slug)
                    ?.data.body
                }
              </React.Fragment>
            </div>
          </section>
          <section className={classNames("all", sty.section__kYf0)}>
            <div className={classNames("all", sty.freeBox___4SrAh)}>
              <PlasmicImg__
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}

                alt={""}
                className={classNames(sty.img)}
                displayHeight={"190px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"190px"}
                loading={"lazy"}
              />

              <div className={classNames("all", sty.freeBox__y9Izt)}>
                <div
                  className={classNames("all", "__wab_text", sty.text___5IWaM)}
                >
                  {"Author"}
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__g5536)}
                >
                  {"Nikita Morell"}
                </div>
                <div
                  className={classNames("all", "__wab_text", sty.text__zTmI)}
                >
                  {"Enter some text"}
                </div>
                <div className={classNames("all", sty.freeBox__tVTbL)}>
                  <PlasmicLink__
                    className={classNames(
                      "all",
                      "a",
                      "a__8kaaM",
                      "__wab_text",
                      sty.link__kWmR5
                    )}
                    component={Link}
                    href={"https://www.plasmic.app/"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"LINKEDIN"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      "all",
                      "a",
                      "a__8kaaM",
                      "__wab_text",
                      sty.link__kiuqr
                    )}
                    component={Link}
                    href={"https://www.plasmic.app/"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"WEBSITE"}
                  </PlasmicLink__>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames("all", sty.section__agqZn)}>
            <div className={classNames("all", sty.freeBox__cxt8C)}>
              <h1
                className={classNames(
                  "all",
                  "h1",
                  "h1__8kaaM",
                  "__wab_text",
                  sty.h1__js3X8
                )}
              >
                {"Get it in your inbox first"}
              </h1>
              <div className={classNames("all", "__wab_text", sty.text__un3Ob)}>
                {
                  "Digging up branding insights, concrete messaging examples, and sharp takes on positioning. Delivered bi-monthly(ish).\r"
                }
              </div>
              <NewsletterFormSection
                data-plasmic-name={"newsletterFormSection"}
                data-plasmic-override={overrides.newsletterFormSection}

                className={classNames(
                  "__wab_instance",
                  sty.newsletterFormSection
                )}
                submitButtonLabel={"Subscribe"}
                successMessage={"Thanks for subscribing!"}
                successMessageColour={"dirt-green"}
              />
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "dirtNav", "img", "newsletterFormSection"],
  dirtNav: ["dirtNav"],
  img: ["img"],
  newsletterFormSection: ["newsletterFormSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dirtNav: typeof DirtNav;
  img: typeof PlasmicImg__;
  newsletterFormSection: typeof NewsletterFormSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicArticlesTemplate__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicArticlesTemplate__VariantsArgs;
    args?: PlasmicArticlesTemplate__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicArticlesTemplate__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicArticlesTemplate__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicArticlesTemplate__ArgProps,
          internalVariantPropNames: PlasmicArticlesTemplate__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicArticlesTemplate__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicArticlesTemplate";
  } else {
    func.displayName = `PlasmicArticlesTemplate.${nodeName}`;
  }
  return func;
}

export const PlasmicArticlesTemplate = Object.assign(
  // Top-level PlasmicArticlesTemplate renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dirtNav: makeNodeComponent("dirtNav"),
    img: makeNodeComponent("img"),
    newsletterFormSection: makeNodeComponent("newsletterFormSection"),

    // Metadata about props expected for PlasmicArticlesTemplate
    internalVariantProps: PlasmicArticlesTemplate__VariantProps,
    internalArgProps: PlasmicArticlesTemplate__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/blog/[slug]",
      pagePath: "/blog/[slug]",
      params: {},
      query: {}
    })
  }
);

export default PlasmicArticlesTemplate;
/* prettier-ignore-end */
