/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8kaaMUEQHxomwqwuKNMozy
// Component: Boo0whzpC_1V

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useMutablePlasmicQueryData } from "@plasmicapp/query";

import { usePlasmicQueries } from "@plasmicapp/react-web/lib/data-sources";
import type {
  PlasmicQuery,
  PlasmicQueryResult
} from "@plasmicapp/react-web/lib/data-sources";
import type { QueryComponentNode } from "@plasmicapp/react-web/lib/data-sources";

import { DirtNav } from "../../sections/DirtNav"; // plasmic-import: CKU2TJ7qFh0A/codeComponent
import { DirtNavLink } from "../../sections/DirtNavLink"; // plasmic-import: djxf9UfRwps8/codeComponent
import NavigationContactButton from "../../NavigationContactButton"; // plasmic-import: etjyWldN73kr/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { NewsletterFormSection } from "../../sections/NewsletterFormSection"; // plasmic-import: XfKpmE3Hd3LP/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicArticlesTemplate.module.css"; // plasmic-import: Boo0whzpC_1V/css

import { fetchContent as __fn_plasmicCms__fetchContent } from "@plasmicpkgs/cms";

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicArticlesTemplate__VariantMembers = {};
export type PlasmicArticlesTemplate__VariantsArgs = {};
type VariantPropType = keyof PlasmicArticlesTemplate__VariantsArgs;
export const PlasmicArticlesTemplate__VariantProps =
  new Array<VariantPropType>();

export type PlasmicArticlesTemplate__ArgsType = {};
type ArgPropType = keyof PlasmicArticlesTemplate__ArgsType;
export const PlasmicArticlesTemplate__ArgProps = new Array<ArgPropType>();

export type PlasmicArticlesTemplate__OverridesType = {
  root?: Flex__<"div">;
  dirtNav?: Flex__<typeof DirtNav>;
  navigationContactButton?: Flex__<typeof NavigationContactButton>;
  customPageStyling?: Flex__<typeof Embed>;
  img?: Flex__<typeof PlasmicImg__>;
  newsletterFormSection?: Flex__<typeof NewsletterFormSection>;
};

export interface DefaultArticlesTemplateProps {}

const $$ = {
  plasmicCms: {
    fetchContent: __fn_plasmicCms__fetchContent
  }
};

export const serverQueryTree: QueryComponentNode = {
  type: "component",
  queries: {
    articles: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsPublicToken: null,
            cmsId: null,
            tableId: null,
            orderBy: null,
            orderDirection: null,
            offset: null
          };
          __composite["cmsPublicToken"] =
            "SEDPH2yp15PlCcWNciTlp1E5wPDR5TvMxlZienZrDz8CxW3LaZkyZan3a8SYXGum1ZR0xOLLh9KmanzfqsQ";
          __composite["cmsId"] = "oddQjnTUVWDpYkuyZHTBcK";
          __composite["tableId"] = "articles";
          __composite["orderBy"] = "publishedDate";
          __composite["orderDirection"] = "desc";
          __composite["offset"] = 0;
          return __composite;
        })()
      ]
    },
    authors: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsId: null,
            cmsPublicToken: null,
            tableId: null
          };
          __composite["cmsId"] = "oddQjnTUVWDpYkuyZHTBcK";
          __composite["cmsPublicToken"] =
            "Oq9HoSuLbH8xdIIUvRFBwjXFzBdrqx4S2jNviKrGncu8V47IRi1QctzJsiHhRH09AZHTuxps8bHVAPU5oGMQ";
          __composite["tableId"] = "authors";
          return __composite;
        })()
      ]
    },
    categories: {
      id: "plasmicCms.fetchContent",
      fn: $$.plasmicCms.fetchContent,
      args: ({ $q, $props, $ctx, $state }) => [
        (() => {
          const __composite = {
            host: "https://data.plasmic.app",
            cmsPublicToken: null,
            cmsId: null,
            tableId: null
          };
          __composite["cmsPublicToken"] =
            "SEDPH2yp15PlCcWNciTlp1E5wPDR5TvMxlZienZrDz8CxW3LaZkyZan3a8SYXGum1ZR0xOLLh9KmanzfqsQ";
          __composite["cmsId"] = "oddQjnTUVWDpYkuyZHTBcK";
          __composite["tableId"] = "categories";
          return __composite;
        })()
      ]
    }
  },
  propsContext: {},
  stateSpecs: [],
  children: []
};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicArticlesTemplate__RenderFunc(props: {
  variants: PlasmicArticlesTemplate__VariantsArgs;
  args: PlasmicArticlesTemplate__ArgsType;
  overrides: PlasmicArticlesTemplate__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $q = usePlasmicQueries(serverQueryTree, { $ctx, $props, $state: null });

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy($q),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_8kaaMUEQHxomwqwuKNMozy",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <DirtNav
            data-plasmic-name={"dirtNav"}
            data-plasmic-override={overrides.dirtNav}

            actions={
              <NavigationContactButton
                data-plasmic-name={"navigationContactButton"}
                data-plasmic-override={overrides.navigationContactButton}

                className={classNames(
                  "__wab_instance",
                  sty.navigationContactButton
                )}
              />
            }
            className={classNames("__wab_instance", sty.dirtNav)}
            logo={"/plasmic/dirt/images/dirtFinalIdentityLogos06Png.png"}
            menuBackground={"dirt-pop"}
            menuImage={"/plasmic/dirt/images/menuImagePng.png"}
            menuLinks={
              <React.Fragment>
                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__tBuBs
                  )}
                  href={"/about"}
                  label={"About"}
                />

                <DirtNavLink
                  className={classNames(
                    "__wab_instance",
                    sty.dirtNavLink__dq5Sc
                  )}
                  href={"/contact"}
                  label={"Contact"}
                />
              </React.Fragment>
            }
            navBackground={"dirt-black"}
            stickyOnScroll={false}
          />

          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
            (() => {
              try {
                return ($q.articles.data || []).filter((a, i) =>
                  $ctx.params.slug
                    ? (a.data.title || "")
                        .toLowerCase()
                        .trim()
                        .replace(/[^a-z0-9]+/g, "-")
                        .replace(/^-|-$/g, "") === $ctx.params.slug
                    : i === 0
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()
          ).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <div
                className={classNames("all", sty.freeBox___4EpJp)}
                key={currentIndex}
              >
                <section className={classNames("all", sty.section___3YlKg)}>
                  <div className={classNames("all", sty.freeBox___6Jh8O)}>
                    <div className={classNames("all", sty.freeBox__c1EJf)}>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__ofBeU
                        )}
                      >
                        <React.Fragment>
                          {
                            $q.categories.data.find(
                              c => c.id === currentItem.data.category
                            )?.data.name
                          }
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__gKpKf
                        )}
                      >
                        {"\u00b7"}
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__qxLTc
                        )}
                      >
                        <React.Fragment>
                          {Math.max(
                            1,
                            Math.ceil(
                              (currentItem.data.body || "")
                                .replace(/<[^>]*>/g, " ")
                                .trim()
                                .split(/\s+/).length / 200
                            )
                          ) + " min read"}
                        </React.Fragment>
                      </div>
                    </div>
                    <h1
                      className={classNames(
                        "all",
                        "h1",
                        "h1__8kaaM",
                        "__wab_text",
                        sty.h1__kTig7
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return currentItem.data.title;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "You won't believe what happens next.";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </h1>
                  </div>
                </section>
                <section className={classNames("all", sty.section__tytWo)}>
                  <div
                    className={classNames("all", "__wab_text", sty.text__xufm9)}
                  >
                    <div
                      className={"__wab_expr_html_text"}
                      dangerouslySetInnerHTML={{
                        __html: `<div class="article-body">${currentItem.data.body || ""}</div>`
                      }}
                    />
                  </div>
                  <Embed
                    data-plasmic-name={"customPageStyling"}
                    data-plasmic-override={overrides.customPageStyling}

                    className={classNames(
                      "__wab_instance",
                      sty.customPageStyling
                    )}
                    code={
                      hasVariant(globalVariants, "screen", "tablet")
                        ? '<style>\r\n  .article-body {\r\n    font-family: "Uncut Sans", sans-serif;\r\n    font-weight: 400;\r\n    font-size: 28px;\r\n    letter-spacing: -0.5px;\r\n    line-height: 38px;\r\n  }\r\n  .article-body a{\r\n    color: #fe5c02;\r\n    text-transform: none;\r\n  }\r\n  .article-body a:hover{\r\n    opacity:0.8;\r\n  }\r\n  .article-body h1, .article-body h2, .article-body h3,\r\n  .article-body h4, .article-body h5, .article-body h6 {\r\n    font-family: "Roboto Condensed", sans-serif;\r\n    text-transform: uppercase;\r\n    letter-spacing: normal;\r\n    color: #5C0004;\r\n  }\r\n  .article-body h2 {\r\n    font-size: 60px;\r\n    font-weight: 700;\r\n  }\r\n  .article-body h3 {\r\n    font-size: 40px;\r\n    font-weight: 700;\r\n  }\r\n  .article-body p {\r\n    opacity: 0.9;\r\n  }\r\n  @media (max-width: 1024px) {\r\n    .article-body { font-size: 24px; line-height: 30px; }\r\n    .article-body h2 { font-size: 40px; }\r\n    .article-body h2 { font-size: 30px; }\r\n  }\r\n  @media (max-width: 640px) {\r\n    .article-body { font-size: 20px; line-height: 26px; }\r\n    .article-body h2 { font-size: 30px; }\r\n    .article-body h2 { font-size: 24px; }\r\n  }\r\n</style>'
                        : '<style>\r\n  .article-body {\r\n    font-family: "Uncut Sans", sans-serif;\r\n    font-weight: 400;\r\n    font-size: 28px;\r\n    letter-spacing: -0.5px;\r\n    line-height: 38px;\r\n  }\r\n  .article-body a{\r\n    color: #fe5c02;\r\n  }\r\n  .article-body a:hover{\r\n    color: #fe5c02;\r\n    opacity:0.8;\r\n  }\r\n  .article-body h1, .article-body h2, .article-body h3,\r\n  .article-body h4, .article-body h5, .article-body h6 {\r\n    font-family: "Roboto Condensed", sans-serif;\r\n    text-transform: uppercase;\r\n    letter-spacing: normal;\r\n    color: #5C0004;\r\n  }\r\n  .article-body h2 {\r\n    font-size: 60px;\r\n    font-weight: 700;\r\n  }\r\n  .article-body h3 {\r\n    font-size: 40px;\r\n    font-weight: 700;\r\n  }\r\n  .article-body p {\r\n    opacity: 0.9;\r\n  }\r\n  @media (max-width: 1024px) {\r\n    .article-body { font-size: 24px; line-height: 30px; }\r\n    .article-body h2 { font-size: 40px; }\r\n    .article-body h2 { font-size: 30px; }\r\n  }\r\n  @media (max-width: 640px) {\r\n    .article-body { font-size: 20px; line-height: 26px; }\r\n    .article-body h2 { font-size: 30px; }\r\n    .article-body h2 { font-size: 24px; }\r\n  }\r\n</style>'
                    }
                  />
                </section>
                <section className={classNames("all", sty.section__kYf0)}>
                  <div className={classNames("all", sty.freeBox___4SrAh)}>
                    <PlasmicImg__
                      data-plasmic-name={"img"}
                      data-plasmic-override={overrides.img}

                      alt={""}
                      className={classNames(sty.img)}
                      displayHeight={"190px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"190px"}
                      loading={"lazy"}
                      src={(() => {
                        try {
                          return $q.authors.data.find(
                            au => au.id === currentItem.data.author
                          )?.data.photo.url;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                    />

                    <div className={classNames("all", sty.freeBox__y9Izt)}>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text___5IWaM
                        )}
                      >
                        {"Author"}
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__g5536
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return $q.authors.data.find(
                                au => au.id === currentItem.data.author
                              )?.data.name;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Nikita Morell";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__zTmI
                        )}
                      >
                        <React.Fragment>
                          {
                            $q.authors.data.find(
                              au => au.id === currentItem.data.author
                            )?.data.bio
                          }
                        </React.Fragment>
                      </div>
                      <div className={classNames("all", sty.freeBox__tVTbL)}>
                        <PlasmicLink__
                          className={classNames(
                            "all",
                            "a",
                            "a__8kaaM",
                            "__wab_text",
                            sty.link__kWmR5
                          )}
                          component={Link}
                          href={(() => {
                            try {
                              return $q.authors.data.find(
                                au => au.id === currentItem.data.author
                              )?.data.linkedInLink;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "https://www.plasmic.app/";
                              }
                              throw e;
                            }
                          })()}
                          legacyBehavior={false}
                          platform={"nextjs"}
                          target={"_blank"}
                        >
                          {"LINKEDIN"}
                        </PlasmicLink__>
                        <PlasmicLink__
                          className={classNames(
                            "all",
                            "a",
                            "a__8kaaM",
                            "__wab_text",
                            sty.link__kiuqr
                          )}
                          component={Link}
                          href={(() => {
                            try {
                              return $q.authors.data.find(
                                au => au.id === currentItem.data.author
                              )?.data.website;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "https://www.plasmic.app/";
                              }
                              throw e;
                            }
                          })()}
                          legacyBehavior={false}
                          platform={"nextjs"}
                          target={"_blank"}
                        >
                          {"WEBSITE"}
                        </PlasmicLink__>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            );
          })}
          <section className={classNames("all", sty.section__agqZn)}>
            <div className={classNames("all", sty.freeBox__cxt8C)}>
              <h1
                className={classNames(
                  "all",
                  "h1",
                  "h1__8kaaM",
                  "__wab_text",
                  sty.h1__js3X8
                )}
              >
                {"Get it in your inbox first"}
              </h1>
              <div className={classNames("all", "__wab_text", sty.text__un3Ob)}>
                {
                  "Digging up branding insights, concrete messaging examples, and sharp takes on positioning. Delivered bi-monthly(ish).\r"
                }
              </div>
              <NewsletterFormSection
                data-plasmic-name={"newsletterFormSection"}
                data-plasmic-override={overrides.newsletterFormSection}

                className={classNames(
                  "__wab_instance",
                  sty.newsletterFormSection
                )}
                submitButtonLabel={"Subscribe"}
                successMessage={"Thanks for subscribing!"}
                successMessageColour={"dirt-green"}
              />
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "dirtNav",
    "navigationContactButton",
    "customPageStyling",
    "img",
    "newsletterFormSection"
  ],
  dirtNav: ["dirtNav", "navigationContactButton"],
  navigationContactButton: ["navigationContactButton"],
  customPageStyling: ["customPageStyling"],
  img: ["img"],
  newsletterFormSection: ["newsletterFormSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  dirtNav: typeof DirtNav;
  navigationContactButton: typeof NavigationContactButton;
  customPageStyling: typeof Embed;
  img: typeof PlasmicImg__;
  newsletterFormSection: typeof NewsletterFormSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicArticlesTemplate__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicArticlesTemplate__VariantsArgs;
    args?: PlasmicArticlesTemplate__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicArticlesTemplate__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicArticlesTemplate__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicArticlesTemplate__ArgProps,
          internalVariantPropNames: PlasmicArticlesTemplate__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicArticlesTemplate__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicArticlesTemplate";
  } else {
    func.displayName = `PlasmicArticlesTemplate.${nodeName}`;
  }
  return func;
}

export const PlasmicArticlesTemplate = Object.assign(
  // Top-level PlasmicArticlesTemplate renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dirtNav: makeNodeComponent("dirtNav"),
    navigationContactButton: makeNodeComponent("navigationContactButton"),
    customPageStyling: makeNodeComponent("customPageStyling"),
    img: makeNodeComponent("img"),
    newsletterFormSection: makeNodeComponent("newsletterFormSection"),

    // Metadata about props expected for PlasmicArticlesTemplate
    internalVariantProps: PlasmicArticlesTemplate__VariantProps,
    internalArgProps: PlasmicArticlesTemplate__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/blog/[slug]",
      pagePath: "/blog/[slug]",
      params: {},
      query: {}
    })
  }
);

export default PlasmicArticlesTemplate;
/* prettier-ignore-end */
