/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8kaaMUEQHxomwqwuKNMozy
// Component: PsrXtMg1_Gbw

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { HeroSection } from "../../sections/HeroSection"; // plasmic-import: oYTAqFgzizOu/codeComponent
import { CompanyCarouselSection } from "../../sections/CompanyCarouselSection"; // plasmic-import: UzUry5mU4ozT/codeComponent
import { BrandItem } from "../../sections/BrandItem"; // plasmic-import: n6yARC8wCw5J/codeComponent
import { InfoSection } from "../../sections/InfoSection"; // plasmic-import: 3w9ZT_4EuJCw/codeComponent
import { PainPointsSection } from "../../sections/PainPointsSection"; // plasmic-import: a6zcK0cc2pSa/codeComponent
import { PainPointCheckbox } from "../../sections/PainPointCheckbox"; // plasmic-import: -4VXY6ZJhgvD/codeComponent
import { SignsCTASection } from "../../sections/SignsCTASection"; // plasmic-import: 3hNXXIJF-DSf/codeComponent
import { TestimonialSection } from "../../sections/TestimonialSection"; // plasmic-import: 19614fshNGrI/codeComponent
import { ThreeReasonsSection } from "../../sections/ThreeReasonsSection"; // plasmic-import: wg-w-3Zg2_WL/codeComponent
import { DirtFrameworkSection } from "../../sections/DirtFrameworkSection"; // plasmic-import: hjSOs7Mv8Nv8/codeComponent
import { DirtProcessSection } from "../../sections/DirtProcessSection"; // plasmic-import: RtT6x1K_HM6p/codeComponent
import { DirtFilesSection } from "../../sections/DirtFilesSection"; // plasmic-import: BPSe7oQrItqb/codeComponent
import { ProsConsSection } from "../../sections/ProsConsSection"; // plasmic-import: qgjtoWkw9uzC/codeComponent
import { FooterSection } from "../../sections/FooterSection"; // plasmic-import: I7Z-mxcvFz5C/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 8kaaMUEQHxomwqwuKNMozy/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: PsrXtMg1_Gbw/css

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  home?: Flex__<"div">;
  heroSection?: Flex__<typeof HeroSection>;
  companiesWeCoveredInDirt?: Flex__<typeof CompanyCarouselSection>;
  painPointsSection?: Flex__<typeof PainPointsSection>;
  signsCtaSection?: Flex__<typeof SignsCTASection>;
  threeReasonsSection?: Flex__<typeof ThreeReasonsSection>;
  dirtFrameworkSection?: Flex__<typeof DirtFrameworkSection>;
  dirtProcessSection?: Flex__<typeof DirtProcessSection>;
  dirtFilesSection?: Flex__<typeof DirtFilesSection>;
  prosConsSection?: Flex__<typeof ProsConsSection>;
  footerSection?: Flex__<typeof FooterSection>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"home"}
          data-plasmic-override={overrides.home}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.home
          )}
        >
          <HeroSection
            data-plasmic-name={"heroSection"}
            data-plasmic-override={overrides.heroSection}
            backgroundImage={"/plasmic/dirt/images/dirtBackPng.png"}
            className={classNames("__wab_instance", sty.heroSection)}
            ctaLabel={"Dig in with a call"}
            description={
              "DIRT is the agency for construction, property, design/build, & building material businesses who want a modern brand to match their capabilities."
            }
            foregroundImage={"/plasmic/dirt/images/dirtFrontPng.png"}
            heading={"Fresh messaging, branding, and positioning"}
            midgroundImage={
              "/plasmic/dirt/images/dirtFinalIdentityLogos06Png.png"
            }
            subheading={"From the ground up"}
          />

          <CompanyCarouselSection
            data-plasmic-name={"companiesWeCoveredInDirt"}
            data-plasmic-override={overrides.companiesWeCoveredInDirt}
            backgroundImage={"/plasmic/dirt/images/cutCompaniesDirtBgPng.png"}
            className={classNames(
              "__wab_instance",
              sty.companiesWeCoveredInDirt
            )}
            heading={"Companies we covered in"}
            highlightedWord={"dirt"}
          >
            <BrandItem
              className={classNames("__wab_instance", sty.brandItem__xo4H1)}
              image={"/plasmic/dirt/images/webflowLogoPng.png"}
              title={"Webflow"}
            />

            <BrandItem
              className={classNames("__wab_instance", sty.brandItem__kuCv1)}
              image={"/plasmic/dirt/images/webflowLogoPng.png"}
              title={"Webflow"}
            />

            <BrandItem
              className={classNames("__wab_instance", sty.brandItem___7Nr7D)}
              image={"/plasmic/dirt/images/webflowLogoPng.png"}
              title={"Webflow"}
            />

            <BrandItem
              className={classNames("__wab_instance", sty.brandItem__qTIp)}
              image={"/plasmic/dirt/images/webflowLogoPng.png"}
              title={"Webflow"}
            />

            <BrandItem
              className={classNames("__wab_instance", sty.brandItem__yl83X)}
              image={"/plasmic/dirt/images/webflowLogoPng.png"}
              title={"Webflow"}
            />

            <BrandItem
              className={classNames("__wab_instance", sty.brandItem__r12W1)}
              image={"/plasmic/dirt/images/webflowLogoPng.png"}
              title={"Webflow"}
            />

            <BrandItem
              className={classNames("__wab_instance", sty.brandItem__zI2R)}
              image={"/plasmic/dirt/images/webflowLogoPng.png"}
              title={"Webflow"}
            />
          </CompanyCarouselSection>
          <InfoSection
            className={classNames("__wab_instance", sty.infoSection__tRzrb)}
            ctaLabel={"Dig in with a call"}
            ctaLink={"/"}
            heading={
              "The next evolution of property, construction, and built-tech is here"
            }
            image={"/plasmic/dirt/images/manSittingOnAChairOnTheMoonJpg.jpg"}
            layout={"imageLeft"}
            richText={
              <React.Fragment>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wkMGr
                  )}
                >
                  {
                    "Building materials, methods, and tech have changed a LOT in the last 100 years."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aUagl
                  )}
                >
                  {
                    "From 3D printing, advanced composites, and self-healing concrete to AI-driven predictive analytics, 5D BIM, and Digital Twins."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fAXw2
                  )}
                >
                  {
                    "But your current brand isn't telling customers any of that. In fact, it's not telling them anything."
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__roSGp
                  )}
                >
                  {
                    "Your business does so much more than your current messaging reflects. "
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eDUmi
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"DIRT is here to change that."}
                    </span>
                  </React.Fragment>
                </div>
              </React.Fragment>
            }
            subheading={"Shouldn't your brand evolve too?"}
          />

          <PainPointsSection
            data-plasmic-name={"painPointsSection"}
            data-plasmic-override={overrides.painPointsSection}
            caption0={"Solid. You\u2019re all good."}
            caption1={"Hmm...Some minor cracks"}
            caption2={"Yep. You've got noticeable damage."}
            caption3={"Things are starting to buckle."}
            caption4={"Serious structural damage."}
            caption5={"Total collapsing."}
            className={classNames("__wab_instance", sty.painPointsSection)}
            heading={"What\u2019s stopping clients from choosing you?"}
            image0={"/plasmic/dirt/images/painPointsBuilding0Jpg.jpg"}
            image1={"/plasmic/dirt/images/painPointsBuilding1Jpg.jpg"}
            image2={"/plasmic/dirt/images/painPointsBuilding2Jpg.jpg"}
            image3={"/plasmic/dirt/images/painPointsBuilding3Jpg.jpg"}
            image4={"/plasmic/dirt/images/painPointsBuilding4Jpg.jpg"}
            image5={"/plasmic/dirt/images/painPointsBuilding5Jpg.jpg"}
            subheading={
              "Check the boxes that feel true to see if DIRT can help:"
            }
          >
            <PainPointCheckbox
              className={classNames(
                "__wab_instance",
                sty.painPointCheckbox__xYxr
              )}
              label={"Trouble scaling beyond word-of-mouth referrals"}
            />

            <PainPointCheckbox
              className={classNames(
                "__wab_instance",
                sty.painPointCheckbox__wNdgU
              )}
              label={
                "Clients don\u2019t \u201cget\u201d what makes you different"
              }
            />

            <PainPointCheckbox
              className={classNames(
                "__wab_instance",
                sty.painPointCheckbox__m3L4Z
              )}
              label={"Losing bids to cheaper competitors"}
            />

            <PainPointCheckbox
              className={classNames(
                "__wab_instance",
                sty.painPointCheckbox__nM1RJ
              )}
              label={"Limited visibility in new markets"}
            />

            <PainPointCheckbox
              className={classNames(
                "__wab_instance",
                sty.painPointCheckbox__cYgsp
              )}
              label={
                "Marketing results don\u2019t match the size of your ambitions"
              }
            />
          </PainPointsSection>
          <SignsCTASection
            data-plasmic-name={"signsCtaSection"}
            data-plasmic-override={overrides.signsCtaSection}
            className={classNames("__wab_instance", sty.signsCtaSection)}
          />

          <TestimonialSection
            authorName={"David Koren"}
            authorPhoto={"/plasmic/dirt/images/davidKorenPhotoJpg.jpg"}
            authorRole={
              "Director of Marketing, DeSimone Consulting Engineering"
            }
            backgroundColor={"dirt-green"}
            body={
              "We struggled to tell our story in a way that felt true to who we are. Now, our website copy is clear, energised, and genuinely reflects our firm.\n\nThe process reconnected our team to what we stand for and gave us real confidence in how we communicate our value.\n\nThank you, Nikita! Our brand finally feels like us."
            }
            className={classNames(
              "__wab_instance",
              sty.testimonialSection__idmN
            )}
            customTextColor={``}
            logo={"/plasmic/dirt/images/deSimoneLogoPng.png"}
            textColor={"dirt-deep"}
          />

          <ThreeReasonsSection
            data-plasmic-name={"threeReasonsSection"}
            data-plasmic-override={overrides.threeReasonsSection}
            className={classNames("__wab_instance", sty.threeReasonsSection)}
          />

          <DirtFrameworkSection
            data-plasmic-name={"dirtFrameworkSection"}
            data-plasmic-override={overrides.dirtFrameworkSection}
            className={classNames("__wab_instance", sty.dirtFrameworkSection)}
          />

          <DirtProcessSection
            data-plasmic-name={"dirtProcessSection"}
            data-plasmic-override={overrides.dirtProcessSection}
            className={classNames("__wab_instance", sty.dirtProcessSection)}
          />

          <DirtFilesSection
            data-plasmic-name={"dirtFilesSection"}
            data-plasmic-override={overrides.dirtFilesSection}
            className={classNames("__wab_instance", sty.dirtFilesSection)}
          />

          <InfoSection
            className={classNames("__wab_instance", sty.infoSection__wf3C9)}
            richText={null}
          />

          <ProsConsSection
            data-plasmic-name={"prosConsSection"}
            data-plasmic-override={overrides.prosConsSection}
            className={classNames("__wab_instance", sty.prosConsSection)}
          />

          <TestimonialSection
            authorName={"Jason Dunlop"}
            authorPhoto={"/plasmic/dirt/images/jasonDunlopPhotoJpg.jpg"}
            authorRole={"President, StudioMX"}
            backgroundColor={"dirt-blue"}
            body={`Since launching the new website, clients have commented on how clear and strong the messaging is.

The process helped us articulate what we’d always known about our practice but never put into words and that clarity has changed how we talk about our business, inside and out.

Huge thanks to Nikita for creating  and her team!`}
            className={classNames(
              "__wab_instance",
              sty.testimonialSection__xAfa
            )}
            customBackgroundColor={``}
            customTextColor={``}
            logo={"/plasmic/dirt/images/studiomxLogoPng.png"}
            textColor={"dirt-deep"}
          />

          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            backgroundColor={``}
            backgroundImage={"/plasmic/dirt/images/footerImagePng.png"}
            bottomRightLink={"/"}
            bottomRightText={"Click here to toss some DIRT on the competition"}
            className={classNames("__wab_instance", sty.footerSection)}
            contactDescription={`Dig what we're doing but don't need us at the moment? Refer a client to DIRT. 

When they sign on, we'll send you a 5% referral fee. (A little thank you for spreading the DIRT)`}
            contactHeading={"Refer & Earn"}
            copyrightText={
              "\u00a9 2025 DIRT Agency. All rights reserved. Built from the ground up."
            }
            description={
              "Tell us your DIRTiest dreams and we'll make them come true:"
            }
            footerDescription={
              "Fresh messaging, branding, and positioning from the ground up."
            }
            footerLogo={"/plasmic/dirt/images/dirtLogoPng.png"}
            heading1={"Brilliant brands don't grow on trees."}
            heading2={"They grow in the DIRT."}
            link1Text={"Work"}
            link2Text={"About"}
            link2Url={``}
            link3Text={"Contact"}
            linksHeading={"Get your hands Dirty"}
            newsletterDescription={
              "Gritty strategic insights to help you win more clients. Delivered with love (and a smidge of mud) once monthly."
            }
            newsletterHeading={"Get DIRT Dispatch"}
            recipientEmail={"hello@thedirtagency.com"}
            separatorImage={"/plasmic/dirt/images/line2Png.png"}
            submitButtonText={"Get Dirty"}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  home: [
    "home",
    "heroSection",
    "companiesWeCoveredInDirt",
    "painPointsSection",
    "signsCtaSection",
    "threeReasonsSection",
    "dirtFrameworkSection",
    "dirtProcessSection",
    "dirtFilesSection",
    "prosConsSection",
    "footerSection"
  ],
  heroSection: ["heroSection"],
  companiesWeCoveredInDirt: ["companiesWeCoveredInDirt"],
  painPointsSection: ["painPointsSection"],
  signsCtaSection: ["signsCtaSection"],
  threeReasonsSection: ["threeReasonsSection"],
  dirtFrameworkSection: ["dirtFrameworkSection"],
  dirtProcessSection: ["dirtProcessSection"],
  dirtFilesSection: ["dirtFilesSection"],
  prosConsSection: ["prosConsSection"],
  footerSection: ["footerSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  home: "div";
  heroSection: typeof HeroSection;
  companiesWeCoveredInDirt: typeof CompanyCarouselSection;
  painPointsSection: typeof PainPointsSection;
  signsCtaSection: typeof SignsCTASection;
  threeReasonsSection: typeof ThreeReasonsSection;
  dirtFrameworkSection: typeof DirtFrameworkSection;
  dirtProcessSection: typeof DirtProcessSection;
  dirtFilesSection: typeof DirtFilesSection;
  prosConsSection: typeof ProsConsSection;
  footerSection: typeof FooterSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "home") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("home"),
  {
    // Helper components rendering sub-elements
    heroSection: makeNodeComponent("heroSection"),
    companiesWeCoveredInDirt: makeNodeComponent("companiesWeCoveredInDirt"),
    painPointsSection: makeNodeComponent("painPointsSection"),
    signsCtaSection: makeNodeComponent("signsCtaSection"),
    threeReasonsSection: makeNodeComponent("threeReasonsSection"),
    dirtFrameworkSection: makeNodeComponent("dirtFrameworkSection"),
    dirtProcessSection: makeNodeComponent("dirtProcessSection"),
    dirtFilesSection: makeNodeComponent("dirtFilesSection"),
    prosConsSection: makeNodeComponent("prosConsSection"),
    footerSection: makeNodeComponent("footerSection"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "DIRT - ",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
