// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../components/plasmic/dirt/PlasmicGlobalContextsProvider";

import { PlasmicArticlesTemplate } from "../../components/plasmic/dirt/PlasmicArticlesTemplate";
import { useRouter } from "next/router";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";
import type { GetStaticPaths, GetStaticProps } from "next";
import { extractPlasmicQueryData } from "@plasmicapp/react-web/lib/prepass";
import { SEO } from "../../components/SEO";
import { seoDefaults } from "@/config/seo-defaults";
import {
  getArticleBySlug,
  getPublishedArticleSlugs,
  type ArticleWithAuthor,
} from "../../utils/plasmic-cms";

export const getStaticProps: GetStaticProps = async context => {
  const slug = context.params?.slug;
  if (typeof slug !== "string") {
    return { notFound: true };
  }

  // Fetch the article's metadata for <SEO>. If it doesn't exist (or was
  // unpublished), 404 rather than render an empty template.
  const articleData = await getArticleBySlug(slug);
  if (!articleData) {
    return { notFound: true, revalidate: 60 };
  }

  // Prefetch the Plasmic CMS queries the template renders (the article body).
  const queryCache = await extractPlasmicQueryData(
    <PageParamsProvider__ route={"/blog/[slug]"} params={context.params}>
      <PlasmicArticlesTemplate />
    </PageParamsProvider__>
  );

  return {
    // Revalidate so edits/new articles publish without a redeploy (ISR).
    props: { queryCache, articleData },
    revalidate: 60,
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  const slugs = await getPublishedArticleSlugs();
  return {
    paths: slugs.map(slug => ({ params: { slug } })),
    // Articles added after build render on first request, then cache.
    fallback: "blocking",
  };
};

function ArticlesTemplate({
  queryCache,
  articleData,
}: {
  queryCache?: any;
  articleData: ArticleWithAuthor;
}) {
  const { article, author, updatedAt } = articleData;
  const authorName = author?.name;
  const authorUrl = author?.website || author?.linkedInLink;
  const canonical = `${seoDefaults.siteUrl}/blog/${article.slug}`;

  return (
    <>
      <SEO
        title={article.title}
        pageName={article.title}
        description={article.excerpt}
        canonical={canonical}
        ogType="article"
        jsonLdType="BlogPosting"
        headline={article.title}
        datePublished={article.publishedDate}
        dateModified={updatedAt}
        {...(authorName
          ? { articleAuthor: { name: authorName, url: authorUrl } }
          : {})}
      />
      <GlobalContextsProvider>
        <PlasmicQueryDataProvider prefetchedCache={queryCache}>
          <PageParamsProvider__
            route={useRouter()?.pathname}
            params={useRouter()?.query}
            query={useRouter()?.query}
          >
            <PlasmicArticlesTemplate />
          </PageParamsProvider__>
        </PlasmicQueryDataProvider>
      </GlobalContextsProvider>
    </>
  );
}

export default ArticlesTemplate;
