// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/dirt/PlasmicGlobalContextsProvider";

import { PlasmicBlog } from "../components/plasmic/dirt/PlasmicBlog";
import { useRouter } from "next/router";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";
import type { GetStaticProps } from "next";
import { extractPlasmicQueryData } from "@plasmicapp/react-web/lib/prepass";
import { SEO } from "../components/SEO";
import {
  getPublishedArticles,
  type ArticleListItem,
} from "../utils/plasmic-cms";

export const getStaticProps: GetStaticProps = async context => {
  const queryCache = await extractPlasmicQueryData(
    <PageParamsProvider__ route={"/blog"} params={context.params}>
      <PlasmicBlog />
    </PageParamsProvider__>
  );
  // Article summaries for the ItemList JSON-LD (newest first).
  const articles = await getPublishedArticles();
  return {
    props: { queryCache, articles },
    // Revalidate so newly published articles appear in the list without a
    // redeploy (ISR).
    revalidate: 60
  };
};

function Blog({
  queryCache,
  articles = [],
}: {
  queryCache?: any;
  articles?: ArticleListItem[];
}) {
  // Use PlasmicBlog to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicBlog are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicBlog is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).

  return (
    <>
      <SEO
        pageName="Blog"
        description="Insights on branding, positioning and messaging for construction, AEC software, property and building-material companies — from the team at DIRT."
        jsonLdType="CollectionPage"
        skipCanonical
        breadcrumbs={[
          { name: "Home", url: "/" },
          { name: "Blog", url: "/blog" },
        ]}
        itemList={articles.map(a => ({
          title: a.title,
          url: `/blog/${a.slug}`,
          datePublished: a.publishedDate,
        }))}
      />
      <GlobalContextsProvider>
        <PlasmicQueryDataProvider prefetchedCache={queryCache}>
          <PageParamsProvider__
            route={useRouter()?.pathname}
            params={useRouter()?.query}
            query={useRouter()?.query}
          >
            <PlasmicBlog />
          </PageParamsProvider__>
        </PlasmicQueryDataProvider>
      </GlobalContextsProvider>
    </>
  );
}

export default Blog;
