// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/dirt/PlasmicGlobalContextsProvider";
import { SEO } from "../components/SEO";

import { PlasmicNewsletter } from "../components/plasmic/dirt/PlasmicNewsletter";
import { useRouter } from "next/router";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";

function Newsletter() {
  // Use PlasmicNewsletter to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicNewsletter are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicNewsletter is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).

  return (
    <>
      {/*
        No skipCanonical here (unlike the other Plasmic pages): this page's
        Plasmic Studio canonical is currently "/about", so SEO must keep
        emitting the correct "/newsletter" canonical. Once the canonical is
        fixed in Studio, add skipCanonical to drop the duplicate.
      */}
      <SEO
        title="DIRT DISPATCH | The Newsletter"
        pageName="DIRT Dispatch — The Newsletter"
        description="DIRT Dispatch takes the dullest parts of the built environment and makes them witty, smart and worth talking about. For construction, ConTech and building-material teams."
      />
      <GlobalContextsProvider>
        <PlasmicQueryDataProvider>
          <PageParamsProvider__
            route={useRouter()?.pathname}
            params={useRouter()?.query}
            query={useRouter()?.query}
          >
            <PlasmicNewsletter />
          </PageParamsProvider__>
        </PlasmicQueryDataProvider>
      </GlobalContextsProvider>
    </>
  );
}

export default Newsletter;
